In [3]:
import numpy as np

In [9]:
array_2d = np.array([
	[1, 2, 3, 4, 5, 6, 7],
    [8, 9, 10, 11, 12, 13, 14]
    ])

print(array_2d)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [19]:
print(array_2d[1, :])

[ 8  9 10 11 12 13 14]
